### ISSUE TITLE
如何区分两类问题？1.核心代词；2.双重否定

### ISSUE THREAD

**Issue by feng-1985** [qhduan/ConversationalRobotDesign#2]
核心代词-示例：
你怎么认识我呢？  -- 核心代词是你
我可以认识你吗？  -- 核心代词是我

双重否定-示例：
我不喜欢这样的回答
我不是不喜欢这样的回答

基于检索的方法，无法区分句子的核心代词指向及双重否定，导致检索的结果不理想，请教您有什么建议吗？

**Comment by qhduan** [comment]
第一个问题，用依存树分析直接分析主谓宾是否就能满足需求

尝试下LTP的demo：

http://ltp.ai/demo.html

第二个问题

一定程度上也可以用依存树 + 规则来解决
依存树是这样，一般句子主要动词作为根，这里“不是”和“不喜欢”都相当于对作为“根”的“喜欢”这个词的描述，那两个否定描述就代表肯定，这是可以作为规则处理的

如果要从统计角度处理就只能积攒预料了

以上是我的看法

**Comment by feng-1985** [comment]
嗯嗯 谢谢解答！也尝试过依存句法判断主谓宾的方法，主要问题在于闲聊中口语化的句子经常省略主语等成分（一句话实际上是两句很短的话，但是中间都不带标点，这种情况也不少），有无标点也对依存句法分析结果有影响，所以分析结果不可控...

**Comment by qhduan** [comment]
猜测，根据不同情况建立规则吧，有标点、无标点，如果出现的可能性并不高的话，应该还是可以提高不少召回率的

**Comment by feng-1985** [comment]
嗯嗯 谢谢！只能慢慢trial and error了。
