### ISSUE TITLE
模型启动失败

### ISSUE THREAD

**Issue by ECNUHP** [qhduan/ConversationalRobotDesign#3]
您好，真的非常感谢您公开自己的源代码
但是我遇到一个很棘手的问题，想请教一下您
我在服务器上训练的模型，服务器上可以跑模型，但是下载到本机之后restore模型报错了。但是本地训练的模型，本地启动模型也是没有问题的，按照道理，保存模型应该和机器没有关系吧
以下是报错的内容：

tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 942326751 vs. calculated on the restored bytes 3112943709
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by qhduan** [comment]
这个至少不是这个项目的问题吧？
