### ISSUE TITLE
小小的质疑

### ISSUE THREAD

**Issue by honghu91** [qhduan/ConversationalRobotDesign#5]
> 基于深度学习 Sequence to Sequence 的聊天机器人
> 它本质是脱胎于神经机器翻译技术（Neural Machine Translation），也就是说本质是把机器翻译的一种语言的一句话到另一种语言的一句话的生成，改为聊天中上一句话到下一句话的生成。
> 
> 它几乎没什么用，甚至说都建议你先去看 AIML 是什么，都比在这耽误时间可能来的要好。
> 
> 因为它：结果不可靠、质量不可控，高质量数据集少，trick 多，对系统能补足的程度小，工程时间成本高，太过独立很难与其他部分契合，人格不一致，结果发散性低……
> 
> 并不是嘛玩意儿沾点深度学习就是好。

ChatGPT等大模型是不是这种技术，现在来看是不是有点误人子弟？

**Comment by qhduan** [comment]
任何事情都是有其时间性的，是时间的函数，您这是在用明朝的剑斩清朝的官啊

作为工程师，在任何一个时间点都应该思考的是如何用当前最好的技术做好事情

即便是科学家，也只能在当时时代有限的情况发展当时的研究

如果说因为一个事情未来可能是好的，就鼓励现在的人去做，这件事其实很多时候是没意义的

哪怕是从今天的角度，我也敢于对于我过去的言论负责，这个言论在当时是有其历史正确性的

另一个例子，100年前就有电池电动车了，但是我就算坐时间机器穿越回100年，我也不会去研发电池电动车，一个时代只能做一个时代的事情

如果你说因为情况改变了，我就有责任清算任何过去的，不符合现状的言论，这是不是有点太难为我了？或者说，我的每个言论，都必须能经得起万年时间的考验，这是不是也太难为我了，我做不到呀

**Comment by honghu91** [comment]
有的时候方向比当前的可用的技术更重要，方向错了，可能努力都是白费的。

在这里不是想争论什么，仅想提醒下作者，知识可以与时俱进，有时间可以修正下，谢谢~

**Comment by qhduan** [comment]
我并无意想跟你争论什么，因为我无意证明自己是对的

实际上你的问题非常好

那么为什么我有时间跟讨论与解释，但是我依然不能去更新这些内容呢？因为我不做到，当然也可以认为是不想做到

btw，这些解释和讨论并不是也并不完全是对你的，更不是针对你，更多的是对我自己的解释，就如同这些“错误”一样，我们的讨论会记录下这些历史

如果我要去更新它们的话，就需要更新太多东西了，我历史积累的内容太多，即便是有人已经明确的指出哪里的位置有问题，我也不想

像我说的，这个世界上的事实往往并不是真的事实，基本上都是基于时间的函数

例如如果我们看到一份1800年的健康指南，你不会相信它是真的，但是在2020年的，我们可能倾向于更信任它，因为它带有时间属性，这是隐含的metadata

其实只要有存在这样的metadata，就已经是针对事件的解释了，或者说，如果人无法分析这种情况就做出假设的话，那我实在是帮助不了

另外，就算它是“错误”的，也是有意义的。错误的历史并不等于没意义的历史，错误的信息并不一定是真的错误的，思考一个事情在当时的历史原因是很重要的，如果能思考到这一层，就更容易更好的解释这个世界了

即便是我承认这个错误，我也不认为我应该修正错误，有时候把一些事实，留给别人，会让精于分析的人更好的分析

为什么当时人们会这么想？为什么当时得到这种结论？假设这是错误的，我们能从这样的错误中学习到什么来避免错误？

---

知识是与时俱进的，但是我并不认为需要对历史做更新，有时候能留下记录也是很重要的

如果你对我一些最新的观点感兴趣，可以通过我的github profile去看我的B站视频

**Comment by honghu91** [comment]
感谢解答，Thanks
